### ISSUE TITLE
Errors when exporting with the default settings (windows)

### ISSUE THREAD

**Issue by hujomaster** [ssz66666/spine-skeleton-exporter#1]
Getting errors when exporting with the default settings for v0.2-e55a2e5 on windows.
[log.txt](https://github.com/ssz66666/spine-skeleton-exporter/files/6371085/log.txt)

**Comment by ssz66666** [comment]
Can you post a copy of the skeleton you used (skeleton json and texture)? The error suggests it couldn't correctly get the size of the skeleton, hence not able to initialise a framebuffer with valid size.

**Comment by hujomaster** [comment]
[ako_spr.zip](https://github.com/ssz66666/spine-skeleton-exporter/files/6380864/ako_spr.zip)

**Comment by ssz66666** [comment]
The skeleton you provided is in Spine 3.8 format but this tool only supports Spine 3.6 skeletons. Additionally, the skeleton is in its binary format (.skel extension) instead of json. 
I recommend checking out other similar tools, e.g. [SuperSpineViewer](https://github.com/Aloento/SuperSpineViewer) or [SpineViewerWPF](https://github.com/kiletw/SpineViewerWPF)
